### PR TITLE
neovim-openresty, luajit2: new formulae

### PR DESCRIPTION
**Pull request by carlocab**

### CODE REVIEW

**Comment by clason** [comment]
Thanks for making this effort! Unfortunately, many of the Lua-heavy plugins do not work with 0.4.4 and require current HEAD (or a recent 0.5-nightly). Would it be possible to test with that as well?

**Comment by clason** [comment]
How do I switch to your brew? Do I just add it as a tap?

**Comment by carlocab** [comment]
Yes. Just `brew tap carlocab/personal`.

**Comment by clason** [comment]
`:ver` claims it's built against `LuaJIT 2.1.0-beta3`, but that's just hard-coded in the built script I guess. Seems to work well, otherwise, from brief initial tests! I don't notice any major slowdowns or errors.

**Comment by carlocab** [comment]
That's because 

    ❯ /usr/local/opt/luajit2/bin/luajit -v
    LuaJIT 2.1.0-beta3 -- Copyright (C) 2005-2020 Mike Pall. https://luajit.org/

My guess is that the OpenResty LuaJIT is actually the LuaJIT master as of 2020-12-29 + small tweaks.

**Comment by clason** [comment]
Looks more like 2020-10-13 + small tweaks (and missing some more recent fixes from LuaJIT master). But it is indeed close enough to LuaJIT for government work. (For now; I am a bit worried they will diverge more and building against OpenResty's fork will no longer work. Last time I asked, neovim was not interested in switching to OpenResty.)

**Comment by carlocab** [comment]
>Last time I asked, neovim was not interested in switching to OpenResty.

How long ago was that? Perhaps enough time has passed without a proper release for it to be worth contemplating a switch again.

**Comment by clason** [comment]
Not long ago; I asked precisely because Mike Pall didn't seem interested in cutting a new beta release.

**Comment by carlocab** [comment]
It doesn't seem like OpenResty LuaJIT does anything API/ABI-breaking, so I imagine it should be a drop-in replacement for anywhere you already use LuaJIT... Not sure it'll open up any new platforms relative to, say, using LuaJIT from the master branch, but at least we get tagged releases?

**Comment by clason** [comment]
Yeah, I looked at the commit history -- they only seem to differ by a handful of recent commits.

The main question is what happens down the road. (We have to worry about Linux packagers, too...)

**Comment by carlocab** [comment]
>The main question is what happens down the road.

I think we can always switch back if the fork is no longer useable? I think worrying about what happens later is a bit premature given that we technically don't really have a useable stable release of LuaJIT right now.

>We have to worry about Linux packagers, too...

Gentoo are actually contemplating switching to OpenResty; it's where I got this idea from.

>There's also the ethical question of promoting a fork over the original.

If the original doesn't suit our purposes anymore because they don't want to cut new releases, I'm not too concerned about this. I mean, we could always ask again if Mike Pall will cut a new release, but I suspect we already know the answer to that.

**Comment by clason** [comment]
> I think we can always switch back if the fork is no longer useable? I think worrying about what happens later is a bit premature given that we technically don't really have a useable stable release of LuaJIT right now.

True; that's a question that'll come up next bump of the LuaJIT dependency by neovim. (Which might be needed as more AARM64 bugs/issues are reported...)

> Gentoo are actually contemplating switching to OpenResty; it's where I got this idea from.

And openSUSE has switched to MoonJIT...

> If the original doesn't suit our purposes anymore because they don't want to cut new releases, I'm not too concerned about this. I mean, we could always ask again if Mike Pall will cut a new release, but I suspect we already know the answer to that.

True; in any case that's a worry for neovim more than for homebrew; at the moment, it looks like that(!) OpenResty release is indeed a drop-in replacement for the LuaJIT commit neovim pulls in. It'd be nice to test that on an M1 just to be safe, though. (I just checked, the latest OpenResty tag contains all commits from our LuaJIT version; the other commits on top of that don't look relevant.)

**Comment by carlocab** [comment]
>And openSUSE has switched to MoonJIT...

I looked at moonjit, actually. It's no longer actively maintained: https://github.com/moonjit/moonjit I think it's safe to assume OpenResty LuaJIT will stay maintained for a while.

>It'd be nice to test that on an M1 just to be safe, though.

It would, yes. Sadly I have no M1 machine either.

>in any case that's a worry for neovim more than for homebrew

I'd have thought using OpenResty would've been in the spirit of Neovim, actually. Especially given that the way it's forked LuaJIT reminds me of the way Neovim has forked Vim...

**Comment by clason** [comment]
> I'd have thought using OpenResty would've been in the spirit of Neovim, actually. Especially given that the way it's forked LuaJIT reminds me of the way Neovim has forked Vim...

:)

(Agreed on MoonJIT.)

**Comment by clason** [comment]
I got someone from the neovim community with an M1 to test it; `brew install --HEAD neovim-openresty` seems to work fine!

**Comment by carlocab** [comment]
Thanks for checking! Given that things seem to be working, is there any chance of Neovim starting to contemplate using the OpenResty fork instead? I imagine it might simplify some things.

If that's not possible, then something else I was thinking of that might help with the continued distribution of Neovim to Homebrew users is the revival of https://github.com/neovim/homebrew-neovim. I don't mind pitching in to help maintain it if it's a viable option.

**Comment by clason** [comment]
I've opened a PR with the OpenResty switch, although not with an intention to merge; just to show it's feasible (and as a canary when things diverge). I believe the majority opinion is still to wait and hope Mike Pall relents and releases a 2.1.0-beta4.

For the nonce, I believe that OpenResty is indeed a simple drop-in replacement, so I at least wouldn't complain if homebrew switched upstream providers.

One issue to keep in mind is that neovim 0.4.4 does not pass its tests on the updated LuaJIT, due to changes in the hashing that leads to different key sorting in tables.

What did `homebrew-neovim` do, precisely? I assume that homebrew itself preferred a formula in core?

**Comment by clason** [comment]
One issue is that LuaJIT2 makes frequent releases (and upstream is not averse to breaking changes), so we'd have to keep the known-good release we build with locked.

**Comment by carlocab** [comment]
>I believe the majority opinion is still to wait and hope Mike Pall relents and releases a 2.1.0-beta4.

Would be nice, but we'll be waiting a while. Not to mention that a `beta4` might not help Homebrew too much. I think the label `beta` would make things a bit too difficult.

>One issue to keep in mind is that neovim 0.4.4 does not pass its tests on the updated LuaJIT, due to changes in the hashing that leads to different key sorting in tables.

Does this have user-visible impacts? Because that might be a reason not to switch Neovim's dependency yet...

>What did homebrew-neovim do, precisely? I assume that homebrew itself preferred a formula in core?

Just as a tap where users can install Neovim from. It'll give Neovim more control over what goes into the Neovim formula. It's not going to make the Neovim formula in homebrew/core go away, but it will be a good alternative if, say, homebrew/core neovim starts building against PUC lua. A Neovim-managed tap will also allow you to build Neovim's stable release against LuaJIT beta, which is currently a no-no in homebrew/core.

>One issue is that LuaJIT2 makes frequent releases (and upstream is not averse to breaking changes), so we'd have to keep the known-good release we build with locked.

That would be a problem for using it with the homebrew/core Neovim formula, since homebrew/core always likes to keep everything as up-to-date as possible...

**Comment by clason** [comment]
> Does this have user-visible impacts? Because that might be a reason not to switch Neovim's dependency yet...

I assume homebrew likes formulas that pass their tests ;) And, yes, this can have actual impacts. For example, another commit before the ARM fixes changed `math.max` semantics, breaking a fairly prominent plugin (packer.nvim, plugin manager)...

> Just as a tap where users can install Neovim from. It'll give Neovim more control over what goes into the Neovim formula. (The one in the Neovim tap, anyway.) It's not going to make the Neovim formula in homebrew/core go away, but it will be a good alternative if, say, homebrew/core neovim starts building against PUC lua. A Neovim-managed tap will also allow you to build Neovim's stable release against LuaJIT beta, which is currently a no-no in homebrew/core.

Hmm. To be honest, that seems like too much duplication of effort? Especially since a simple `make; make install` from a source checkout works just fine... (Using homebrew to install the handful of build dependencies, of course ;))

We might have to revisit if homebrew/core insists on PUC Lua, since that would be like a distro shipping a debug build of a 3D game (or selling Cyberpunk 2077 to current-gen console owners :P)  -- meaning we'd ask homebrew _not_ to ship such a neovim build and make the tap the only official source.

> ...
> That would be a problem for using it with the homebrew/core Neovim formula, since homebrew/core always likes to keep everything as up-to-date as possible...

To be honest again, this is starting to sound like a strong argument against making LuaJIT an external dependency in homebrew and for just baking it in statically from the LuaJIT (or LuaJIT2) tag we specify in the build script. (It _is_ meant as an embedded scripting language, after all :P)

**Comment by carlocab** [comment]
>meaning we'd ask homebrew not to ship such a neovim build and make the tap the only official source

I can already tell you that that's not going to happen. However, hopefully having to ask will not be made necessary at any point.

>this is starting to sound like a strong argument against making LuaJIT an external dependency in homebrew

Fine with me.

>It is meant as an embedded scripting language

Yes, I think this is a big part of what other Homebrew maintainers don't really understand that makes the lua et al formulae not really a good fit for the way Homebrew does things. (See, for example, the PR where `lua@5.1` is deprecated.) Of course, my personal view is that we should just make exceptions for the lua formulae, but I think I'm in the minority there.

**Comment by clason** [comment]
> I can already tell you that that's not going to happen. Other developers have asked in the past, and their software is still packaged in Homebrew. However, hopefully having to ask will not be made necessary at any point.

Yeah, I'm also hoping it won't come to that. Homebrew is the biggest selling point for macOS (I rely on it much more than on the App Store; I can live without the latter but not without the former), and it's good that neovim is included.

But it's hard to stress how much of a difference LuaJIT vs PUC Lua makes, and the neovim ecosystem is starting to leverage that in exciting ways (like an in-process pure-Lua fzf.vim replacement, which can call compiled fzy sorter using FFI -- that just wouldn't be possible with PUC Lua).

> Yes, I think this is a big part of what other Homebrew maintainers don't really understand that makes the lua et al formulae not really a good fit for the way Homebrew does things. (See, for example, the PR where `lua@5.1` is deprecated.) Of course, my personal view is that we should just make exceptions for the lua formulae, but I think I'm in the minority there.

Yeah, that is indeed hard to convey (it comes up in chat with some frequency). Not only are Lua 5.x effectively different languages, Mike Pall doesn't seem interested in ABI stability even within a version 😞 

(And it's not just homebrew -- the discussions with openSUSE maintainers are even more heated...) 

Do you have any suggestions how we could go about convincing them? Maybe start with a tap with baked-in LuaJIT?

**Comment by carlocab** [comment]
>how much of a difference LuaJIT vs PUC Lua makes

Oh, don't worry, I know. In fact, performance regressions were the first thing I brought up in the thread about replacing LuaJIT.

>Do you have any suggestions how we could go about convincing them? Maybe start with a tap with baked-in LuaJIT?

I guess a start would be finding the right commit hash for LuaJIT you need (though I guess you already know this) and vendor that in as a resource in the Neovim formula at homebrew/core. If that enables a build on ARM, then I think the PR that does this will sell itself. The current Neovim release can be patched if it needs to be.

**Comment by clason** [comment]
> Oh, don't worry, I know. In fact, performance regressions were the first thing I brought up in the thread about replacing LuaJIT.

I was thinking of the other maintainers ;)

> I guess a start would be finding the right commit hash for LuaJIT you need (though I guess you already know this) and vendor that in as a resource in the Neovim formula at homebrew/core. If that enables a build on ARM, then I think the PR that does this will sell itself. The current Neovim release can be patched if it needs to be.

Indeed, it's https://github.com/LuaJIT/LuaJIT/commit/1d8b747c161db457e032a023ebbff511f5de5ec2 (although I'd not be averse to replacing this with the latest OpenResty release if you think that'd grease the wheels; I'm fairly certain now these are functionally identical). We haven't backported the ARM fixes to the 0.4 release branch, but this might be an argument for it.

Would I just add this as a resource block like `luv`? I'd probably have to copy the build block from the LuaJIT formula, too?

**Comment by carlocab** [comment]
>Would I just add this as a resource block like luv? I'd probably have to copy the build block from the LuaJIT formula, too?

Yes, and yes. You may not need all of the LuaJIT formula's install block. How does Neovim's non-Homebrew build handle LuaJIT? If Neovim has build scripts that also build the appropriate version of LuaJIT, it may just make sense to replicate that.

>We haven't backported the ARM fixes to the 0.4 release branch, but this might be an argument for it.

Yup. Getting the release to build on ARM is probably not strictly necessary to get the PR that you want merged at homebrew/core, but it would be a lot harder to say no to if it did.

> I'd not be averse to replacing this with the latest OpenResty release

I'm no longer as convinced of this given

>LuaJIT2 makes frequent releases (and upstream is not averse to breaking changes), so we'd have to keep the known-good release we build with locked

It might also be a harder sell if it's not expressly recommended by Neovim (though I suppose you could help with that?).

**Comment by clason** [comment]
> Yes, and yes. You may not need all of the LuaJIT formula's install block. How does Neovim's non-Homebrew build handle LuaJIT? If Neovim has build scripts that also build the appropriate version of LuaJIT, it may just make sense to replicate that.

It's an about 150 line CMake file, mostly architecture-dependent case distinctions. Since homebrew has much more experience with Darwin architecture, I'd trust you over that :)

> Yup. Getting the release to build on ARM is probably not strictly necessary to get the PR that you want merged at homebrew/core, but it would be a lot harder to say no to if it did.

Makes sense; so I'll see about backporting the changes first.

> I'm no longer as convinced of this given
> 
> > LuaJIT2 makes frequent releases (and upstream is not averse to breaking changes), so we'd have to keep the known-good release we build with locked
> 
> It might also be a harder sell if it's not expressly recommended by Neovim (though I suppose you could help with that?).

Yeah, I think we could get a "works also with LuaJIT2 v2020-12-29" imprimatur on the build instructions. But all things being equal, keeping upstream in sync would be preferable, of course.

**Pull request closed without merging**
